format = """
[](bold eva_green)\
$os\
$username\
[](bold bg:eva_lavender fg:eva_green)\
$directory\
$git_branch\
$git_status\
[ ](bold fg:eva_orange)\
$line_break\
$character"""

palette = "eva01_pastel"
add_newline = true

[palettes.eva01_pastel]
eva_fg_dark = "#0F1020"
eva_text = "#E0DEF4"
eva_muted = "#9A86B8"
eva_base = "#191724"
eva_surface = "#1F1D2E"
eva_overlay = "#26233A"
eva_purple_dark = "#4B3A68"
eva_purple = "#7C5FB8"
eva_purple_soft = "#B48DDB"
eva_lavender = "#C4A7E7"
eva_green_dark = "#304D3A"
eva_green = "#A3D977"
eva_green_soft = "#6FAF6E"
eva_orange = "#F6C177"
eva_error = "#7C5FB8"

[os]
disabled = false
style = "bold bg:eva_green fg:eva_fg_dark"
format = "[$symbol]($style)"

[os.symbols]
Macos = "󰀵 "
Arch = " "
CachyOS = " "
Linux = " "

[username]
show_always = true
style_user = "bg:eva_green fg:eva_fg_dark bold"
style_root = "bg:eva_green fg:eva_fg_dark bold"
format = "[ $user ]($style)"

[directory]
style = "bold bg:eva_lavender fg:eva_fg_dark"
format = "[ $path ]($style)"
truncation_length = 0
truncation_symbol = "…/"
truncate_to_repo = false

[directory.substitutions]
Documents = "󰈙 "
Downloads = " "
Music = "󰝚 "
Pictures = " "
Developer = "󰲋 "
code = "󰲋 "

[git_branch]
symbol = ""
style = "bold bg:eva_orange fg:eva_fg_dark"
format = "[](bold bg:eva_orange fg:eva_lavender)[ $symbol $branch ]($style)"

[git_status]
style = "bold bg:eva_orange fg:eva_fg_dark"
format = "[$all_status$ahead_behind ]($style)"

[character]
success_symbol = "[❯](bold eva_green)"
error_symbol = "[❯](bold eva_error)"
vimcmd_symbol = "[❮](bold eva_lavender)"

[cmd_duration]
show_milliseconds = true
format = "[$duration]($style)"
style = "bg:eva_purple_soft fg:eva_fg_dark bold"
