color0 #191724
color1 #7c5fb8
color2 #a3d977
color3 #f6c177
color4 #b48ddb
color5 #7c5fb8
color6 #6faf6e
color7 #f2eaff
color8 #9a86b8
color9 #c4a7e7
color10 #a3d977
color11 #f6c177
color12 #c4a7e7
color13 #b48ddb
color14 #c4a7e7
color15 #f7efff

cursor                #f6c177
cursor_text_color     #0f1020
background            #141218
foreground            #f2eaff
selection_foreground  #f2eaff
selection_background  #4b3a68
active_border_color   #c4a7e7
inactive_border_color #4b3a68
url_color             #a3d977

active_tab_foreground   #0f1020
active_tab_background   #7c5fb8
inactive_tab_foreground #9a86b8
inactive_tab_background #26233a
cursor_trail_color      #c4a7e7
