#!/usr/bin/env bash

CONFIG_DIR="${CONFIG_DIR:-$HOME/.config/sketchybar}"
PLUGIN_DIR="$CONFIG_DIR/plugins"
source "$CONFIG_DIR/colors.sh"

sketchybar --bar \
  position=top \
  height=34 \
  topmost=on \
  color="$BAR_BG" \
  blur_radius=0 \
  sticky=on \
  margin=0 \
  y_offset=0 \
  padding_left=14 \
  padding_right=14

sketchybar --default \
  icon.font="Liga SFMono Nerd Font:Bold:13.0" \
  icon.color="$TEXT" \
  label.font="Liga SFMono Nerd Font:Bold:12.0" \
  label.color="$TEXT" \
  background.color="$ITEM_BG" \
  background.corner_radius=12 \
  background.height=24 \
  background.padding_left=6 \
  background.padding_right=6 \
  padding_left=6 \
  padding_right=6

sketchybar --add event yabai_space_change

sketchybar --add item power left \
  --set power \
    icon="⏻" \
    icon.font="Liga SFMono Nerd Font:Bold:15.0" \
    icon.padding_left=7 \
    icon.padding_right=7 \
    label.drawing=off \
    script="$PLUGIN_DIR/power_item.sh" \
    click_script="$HOME/.local/bin/rice-power-dashboard toggle"

sketchybar --subscribe power mouse.entered mouse.exited

sketchybar --add item clock left \
  --set clock \
    icon.drawing=off \
    label.padding_left=9 \
    label.padding_right=9 \
    update_freq=30 \
    script="$PLUGIN_DIR/clock.sh"

for sid in 1 2 3 4 5 6 7 8 9; do
  sketchybar --add item "space.$sid" left \
    --set "space.$sid" \
      icon="●" \
      icon.font="Liga SFMono Nerd Font:Bold:16.0" \
      icon.padding_left=5 \
      icon.padding_right=5 \
      label.drawing=off \
      background.drawing=off \
      click_script="$HOME/.local/bin/rice-yabai-space $sid" \
      script="$PLUGIN_DIR/yabai_space.sh $sid" \
    --subscribe "space.$sid" yabai_space_change
done

sketchybar --add bracket spaces \
  space.1 space.2 space.3 space.4 space.5 space.6 space.7 space.8 space.9 \
  --set spaces \
    position=left \
    background.color="$ITEM_BG" \
    background.corner_radius=12 \
    background.height=24 \
    background.padding_left=8 \
    background.padding_right=8

sketchybar --add item battery right \
  --set battery \
    icon.font="Liga SFMono Nerd Font:Bold:13.0" \
    icon.padding_left=7 \
    icon.padding_right=4 \
    label.padding_right=8 \
    update_freq=10 \
    script="$PLUGIN_DIR/battery.sh" \
  --subscribe battery power_source_change system_woke

sketchybar --add item weather right \
  --set weather \
    icon="☼" \
    icon.padding_left=7 \
    icon.padding_right=4 \
    label.padding_right=8 \
    update_freq=600 \
    script="$PLUGIN_DIR/weather.sh"

sketchybar --add item brightness right \
  --set brightness \
    icon="☀" \
    icon.padding_left=7 \
    icon.padding_right=4 \
    label.padding_right=8 \
    update_freq=30 \
    script="$PLUGIN_DIR/brightness.sh"

sketchybar --add item volume right \
  --set volume \
    icon="♪" \
    icon.padding_left=7 \
    icon.padding_right=4 \
    label.padding_right=8 \
    update_freq=10 \
    script="$PLUGIN_DIR/volume.sh"

sketchybar --add item wallpaper_rotation left \
  --set wallpaper_rotation \
    drawing=off \
    update_freq=1800 \
    script="$PLUGIN_DIR/wallpaper_rotation.sh"

sketchybar --update
