background_opacity          0.6
pixel_scroll                yes
momentum_scroll             0.96
touch_scroll_multiplier     0.85
wheel_scroll_multiplier     2.0
cursor_trail                1
cursor_trail_decay          0.1 0.4
cursor_trail_start_threshold 1
cursor_trail_color          #6e3c37
cursor_blink_interval       0.5 ease-in-out
cursor_stop_blinking_after  0
window_padding_width        25

include themes/eva01.conf

confirm_os_window_close 0

map ctrl+c copy_and_clear_or_interrupt
map ctrl+v send_text all \x16
map ctrl+shift+v paste_from_clipboard
map ctrl+x combine : copy_to_clipboard : clear_selection
